language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: ACbiW+f/DO/ruxYtzQzLkKQrSyYGlt/W1dY9ou4IvFUVByMUwIIPlhonMQwq6nbjgE06/wpohdm7Geelr4Zxa8kFzTm0deQD8cc5W9/6Vmeh0VQ9+pW+XERNFyBYfMVURFedkDaLwBmiHOeiYmGXEAvmDvXG1C7oeX/axIZlilk=
  - secure: XyGIQPD9mvMTTf0teY3fpL194IjH/m9Ka5nNI7eNVpGO0tyAfUbw9MFA+FpqOy0UgsJ74yNxuZvV3tDSjTjxcJ9uapetZUTl5slIPuSatxcE+opsJpxVW0uAxQCvsVnWfK6LJ3UXC6tDpnObYN8nvwNK1M2xO0GXimXL/EJFxj8=
